name: Pipeline

on: push

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run
      run: python hello.py
    
  build: 
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with: 
        name: hello
        path: .

  
